### ISSUE TITLE
Syntax error in app/code/community/Cocote/Feed/Model/Observer.php

### ISSUE THREAD

**Issue by nelero** [Cocote-Team/Magento1Plugin#2]
Hi,
we received two errors : 

PHP Parse error:  syntax error, unexpected '{' in /home/www/client/www/www/app/code/community/Cocote/Feed/Model/Observer.php on line 251
it refers to this line : 
```
    finally {
            restore_error_handler();
        }

```
we removed the finally

PHP Parse error:  syntax error, unexpected '[', expecting ')' in app/code/community/Cocote/Feed/Model/Observer.php on line 349. it refers to this line :
  
`$allCategories = Mage::getModel('catalog/category')->getCollection()->addAttributeToSelect(['name']);
`

Square brackets are not intended nor justified in this use case.
We removed the brackets and it's ok : 

`$allCategories = Mage::getModel('catalog/category')->getCollection()->addAttributeToSelect('name');
`

**Comment by jakilcz** [comment]
Hi
Can i ask what version of php do You have to have issue with "finally"?

**Comment by nelero** [comment]
Yes, PHP 5.4
