### ISSUE TITLE
characters & not escaped : throwing XML errors during generation

### ISSUE THREAD

**Issue by nelero** [Cocote-Team/Magento1Plugin#3]
Some categories name and keywords contains special characters like & and are not escaped before adding them in xml, causing errors during generation.

file app/code/community/Cocote/Feed/Model/Observer.php
function generateFeed
around line 134, adding htmlspecialchars :
`$currentprod->appendChild($domtree->createElement('keywords', htmlspecialchars($product->getData('meta_keyword'))));`

around line 167 adding htmlspecialchars : 
`$currentprod->appendChild($domtree->createElement('category', htmlspecialchars($catName)));`

**Comment by jakilcz** [comment]
we'll add it to the files, thanks
