### ISSUE TITLE
SSL : cocote script is loaded without https

### ISSUE THREAD

**Issue by nelero** [Cocote-Team/Magento1Plugin#4]
Hi,
we're receiving this error in the console, while activating the module on a https website : 

`Mixed Content: The page at 'https://www.mywebsite.com/' was loaded over HTTPS, but requested an insecure script 'http://js.cocote.com/script-fr.min.js'. This request has been blocked; the content must be served over HTTPS.`

Thanks

**Comment by jakilcz** [comment]
This thing has been fixed 8 days ago:
Check here:
https://github.com/Cocote-Team/Magento1Plugin/blob/master/app/design/frontend/base/default/template/cocote/cocote.phtml

Please update to last version.

**Comment by nelero** [comment]
Great.
We only pull updates when there is more thaï one fix To reduce recipe time.
We il do the update next week
Thanks
